# Generated by Django 4.1.7 on 2023-10-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('AdvID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('AdvName', models.TextField(max_length=70)),
                ('AdvTelNo', models.CharField(max_length=15)),
                ('AdvEmailAddr', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('CompanyName', models.TextField(max_length=70)),
                ('CompanyAddr', models.TextField(max_length=100)),
                ('CompanySector', models.CharField(max_length=30)),
                ('CompanyTelNo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudID', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('StudName', models.TextField(max_length=70)),
                ('StudCourse', models.TextField(max_length=50)),
                ('StudMentor', models.TextField(max_length=70)),
                ('StudEmailAddr', models.CharField(max_length=30)),
                ('StudTelNo', models.CharField(max_length=15)),
                ('BorangJawapanSyarikat', models.FileField(upload_to='BorangJawapanSyarikat/')),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.CharField(max_length=15)),
                ('EndDate', models.CharField(max_length=15)),
                ('Session', models.TextField(max_length=50)),
                ('Salary', models.FloatField()),
                ('ProjectBrief', models.TextField(max_length=300)),
                ('AdvID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.advisor')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.company')),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.student')),
            ],
        ),
    ]
