# Generated by Django 4.1.7 on 2023-10-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERNsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPLOADBYADMIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='ADMIN/pdfs/')),
            ],
        ),
        migrations.AlterField(
            model_name='internship',
            name='ProjectBrief',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='Salary',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
