# Generated by Django 4.1.7 on 2023-10-16 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTERNsystem', '0002_uploadbyadmin_alter_internship_projectbrief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='AdvID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.advisor'),
        ),
        migrations.AlterField(
            model_name='uploadbyadmin',
            name='pdf',
            field=models.FileField(upload_to='ADMIN/INTERN APPLICATION PREQUISITE/'),
        ),
    ]
