# Generated by Django 4.1.7 on 2023-10-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('INTERNsystem', '0004_remove_student_borangjawapansyarikat_student_studimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPLOADBYSTUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorangJawapanSyarikat', models.FileField(upload_to='Borang Jawapan Syarikat Pelajar/')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.company')),
                ('StudID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='INTERNsystem.student')),
            ],
        ),
    ]
