# Generated by Django 4.1.7 on 2023-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERNsystem', '0005_uploadbystudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='Salary',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
