# Generated by Django 4.1.7 on 2023-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INTERNsystem', '0006_alter_internship_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='Salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
